### ISSUE TITLE
What kind of Shoestring Service Module is the MQTT Broker?

### ISSUE THREAD

**Issue by tobyaharris** [DigitalShoestringSolutions/sm_mqtt_broker#6]
As I try to get my head around the [Architecture Specification](https://github.com/DigitalShoestringSolutions/architecture-specification), I'm wondering how to classify this Service Module.

The conflicting points are:
1. It appears to be established and accepted as a standard shoestring service module
2. It does not conform to the minimum requirement of such a module: that it meets the definition of one of [the categories presented by the architecture](https://github.com/DigitalShoestringSolutions/architecture-specification/blob/main/decisions/0005-service-module-types.MD#service-module-types) 

Evidence for 1:
  a. It is a github repo under DigitalShoestringSolutions with prefix `sm_` to the name that has been present for over 18 months.
  b. It runs in a docker container, has a `docker-compose` snippet with features consistent with other service modules (internal networking, logging, restart policy), and otherwise resembles the standard service module structure (cc standards working document).
  c. Many solutions ([including flagship](https://github.com/DigitalShoestringSolutions/PowerMonitoring/tree/f09dbbd8c974922ef8fac57329dd99e2a2b3cd27)) treat it as a service module, including it in a directory alongside other service modules and adopting the `docker-compose` snippet into the solution's `docker-compose.yml`, as with the other service modules.

Evidence for 2: 
The [available types of service module](https://github.com/DigitalShoestringSolutions/architecture-specification/blob/main/decisions/0005-service-module-types.MD#service-module-types) are:
- ***Sensing*** - Sensing service modules generate new data through sensing. This data can be measured variables or detected events. These measurements/events can be related to products, processes, equipment, or the operating environment.
- ***Data Input*** - Data input service modules get existing data into a Shoestring solution. This data can be from files or other systems. The service module can actively fetch this data, or provide an endpoint where this data can be submitted.
- ***Data Storage*** - Data storage service modules capture and record data so that it can be used later. They also provide an interface that can be used to interrogate this historic data.
- ***Analysis*** - Analysis service modules derive information and insights from data. This can be live (in response to requests or events) or periodic/scheduled.
- ***Decision Making*** - Decision making service modules make decisions. A solution could either act directly on theses decisions to do things automatically, or present them as potential/suggested options to a user.
- ***Data Output*** - Data output service modules are used to export data from Shoestring solutions. This data can be output to other systems or as reports/files. The service module can actively send this data or provided an endpoint where it can be fetched from.
- ***Actuation*** - Actuation service modules perform or trigger actions. This can be in the form of direct actions or as signals that trigger/control other systems. 
- ***User Interface*** - User interface service modules are used to get inputs from people and provide outputs to them. This could be through dashboards, forms, physical/digital buttons, lights, alarms, etc. 

Reading the definitions above, arguments could be made that an MQTT broker is Data Input, Data Output or Actuation module, though I feel an MQTT broker is not what these types are trying to target. 

My workaround so far has been to [tag this as "Data Transfer"](https://github.com/DigitalShoestringSolutions/starter-solution-template/blob/232987cf08e534a5a493d43541a0a5141ae05d5f/recipe.txt#L8), knowing that this is not a standard category. 

As the discussion over _what is a service module_ continues, I would like to hear about how this one fits in.

**Comment by Greg-Hawkridge** [comment]
It's not a service module - see DigitalShoestringSolutions/architecture-specification#7. This would have been more efficient as a quick question over teams.
